name: Pylint
author: Eduardo Pignatelli
description: Runs pylint on all *.py files


runs:
  using: "composite"
  steps:
  - run: |
      pip install pylint
      MESSAGE=$(pylint -ry $(git ls-files '*.py') ||:)
      echo "$MESSAGE"
    shell: bash -l {0}

