name: Compliance
author: Eduardo Pignatelli
description: Runs pylint on the files positive to diff between the current branch and the main one

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - run: |
        pip install pylint
        MESSAGE=$(pylint `git diff --name-only --diff-filter=d main... | grep -E '\.py$' | tr '\n' ' '` ||:)

        echo 'MESSAGE<<EOF' >> $GITHUB_ENV
        echo "<pre><code>$MESSAGE</code></pre>" >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
        echo "Printing PR message: $MESSAGE"
      shell: bash

    - uses: mshick/add-pr-comment@v2
      with:
        issue: ${{ github.event.pull_request.number }}
        message: ${{ env.MESSAGE }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
