---
name: Continuous Integration (CI) and Continuous Deployment (CD)
description: >-
  Add or change CI/CD workflows.
labels:
- ci

body:
- type: textarea
  attributes:
    label: Description
    description: >-
      A concise description of what of what you would like to add or change.