blank_issues_enabled: false
contact_links:
  - name: Have questions or want to have a chat?
    url: https://github.com/epignatelli/helx/discussions
    about: Please ask questions on the Discussions tab