name: Examples

on:
  workflow_call:

jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
    - name: Run examples
      run: |
        wandb login ${{ secrets.WANDB_API_KEY }}
        for f in examples/*.py; do python $f; done