name: Setup

on:
  workflow_call:

jobs:
  setup:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}

    steps:

    - uses: actions/checkout@v3

    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-version: latest
        environment-file: environment.yml
        activate-environment: helx
        auto-activate-base: false

    - name: Setup helx
      run: |
        pip install . -v

        helx-download-extras

        conda env config vars set LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.mujoco/mujoco210/bin
        conda env config vars set MJLIB_PATH=$HOME/.mujoco/mujoco210/bin/libmujoco210.so
        conda env config vars set MUJOCO_PY_MUJOCO_PATH=$HOME/.mujoco/mujoco210
        conda env config vars set LD_PRELOAD=$CONDA_PREFIX/x86_64-conda-linux-gnu/sysroot/usr/lib64/libGLdispatch.so.0
