name: CD

on:
  release:
    types: [published]

jobs:
  test:
    uses: ./.github/workflows/CI.yml

  publish:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      max-parallel: 5
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11"]
    if: {{ needs.test.result == 'success'  }}
    steps:
      - uses: actions/checkout@v3

      - name: Build package
        run: python3 -m pip install --upgrade build && python3 -m build

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_KEY }}
