name: CD

on:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          default_bump: "minor"
          dry_run: true
      - name: Fix tag name
        run: |
          CURRENT_TAG_NAME="${{ steps.tag_version.outputs.new_tag }}"
          FIXED_TAG_NAME="$(echo $CURRENT_TAG_NAME | grep -Eo '([0-9]+.[0-9]+\.[0-9]+)')"
          CHANGELOG="${{ steps.tag_version.outputs.changelog }}"

          echo 'CHANGELOG<<EOF' >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

          echo 'FIXED_TAG_NAME<<EOF' >> $GITHUB_ENV
          echo "$FIXED_TAG_NAME" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.FIXED_TAG_NAME }}
          name: ${{ env.FIXED_TAG_NAME }}
          body: ${{ env.CHANGELOG }}

# see:
# https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/
# https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
# for
  publish:
    needs: release
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      max-parallel: 3
      matrix:
        python_version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
      - name: Build wheel and sdist
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          password: ${{ secrets.PYPI_API_KEY }}
