name: Triage

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.TRIAGE_KEY }}

jobs:
  assign-project:
    runs-on: ubuntu-latest
    steps:
    - name: Get priority
      run: |
        case ${{ github.event.issue.label }} in
          'bug' || 'installation/build' || 'performance')
            echo "PRIORITY=P0" >> $GITHUB_ENV
            ;;
          'feature' || 'documentation' || 'test' || 'ci')
            echo "PRIORITY=P1" >> $GITHUB_ENV
            ;;
          'style' || 'refactor' || 'revert' || 'chore')
            echo "PRIORITY=P2" >> $GITHUB_ENV
            ;;
          *)
            echo "PRIORITY=Triage" >> $GITHUB_ENV
            ;;
        esac
    - uses: srggrs/assign-one-project-github-action@1.2.1
      with:
        project: 'https://github.com/users/epignatelli/projects/7'
        column_name: ${{ env.PRIORITY }}
  assign-assignee:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.TRIAGE_KEY }}
          assignees: ${{ github.actor }}
